source 'https://rubygems.org'

ruby '2.4.3'
gem 'rails'
gem 'pg'
gem 'puma'
gem 'bootsnap', require: false
gem 'sass-rails'
gem 'uglifier'
gem 'jquery-rails'
gem 'jbuilder'
gem 'devise'
gem 'coffee-rails'
gem 'geocoder'
gem 'acts-as-taggable-on'
gem 'carrierwave'
gem 'mini_magick'
gem 'fog-aws'
gem 'webpacker'
gem "i18n-js"
gem 'tzinfo-data'
gem 'active_link_to'
gem 'kaminari'
gem 'activeadmin'
gem 'omniauth-facebook'
gem 'activeadmin_addons'
gem 'redis-rails'
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'twilio-ruby'
gem "figaro"
gem 'bootstrap', '~> 4.1.1'
gem 'activeadmin_quill_editor'

group :development, :test do
  gem 'byebug'
  gem 'faker'
  gem 'spring'
  gem 'derailed'
end
