development:
  secret_key_base: 
  FACEBOOK_APP_ID: 
  FACEBOOK_APP_SECRET: 
test:
  secret_key_base: 
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_APP_ID: <%= ENV["FB_KEY"] %>
  FACEBOOK_APP_SECRET: <%= ENV["FB_SECRET"] %>
