# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ada79d3c73512133057c946240e9d5f9875837f623a14ac0cde6f06646589910f2529bbd7955c33edb92bbbc930fe16c4777aae91cf5ea1eb99e11ed8738ed12
  FACEBOOK_APP_ID: 305545103281539
  FACEBOOK_APP_SECRET: 06a268792e93c69c15bdd39a670a8505

test:
  secret_key_base: c5b8df0dcd93aff43d005b4a2962d6bffee91cfd8f3a20d3ac8b6609ddd353b821c1719db843e1077200814f96db94aeec49c7365f983e10ce8add065b7228c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_APP_ID: <%= ENV["FB_KEY"] %>
  FACEBOOK_APP_SECRET: <%= ENV["FB_SECRET"] %>
